import { ArrowLeft } from "lucide-react";

const contactEmail = "templareddy@gmail.com";

function LegalShell({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) {
  return <main className="legal-shell"><header className="legal-header"><a href="/" className="legal-back"><ArrowLeft size={16} /> Back to Edison</a><span className="legal-mark">edison<span>•</span></span></header><article className="legal-article"><p className="legal-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="legal-updated">Last updated: August 19, 2026</p><p className="legal-notice">Working draft — review with qualified legal counsel before relying on it in production.</p>{children}</article></main>;
}

export function PrivacyPolicy() {
  return <LegalShell eyebrow="Edison / privacy" title="Privacy Policy"><section><h2>1. What this policy covers</h2><p>This policy explains how Edison handles information collected through the Edison website and waitlist. Edison is still in an early-access stage, so this policy applies to the waitlist and related communications.</p></section><section><h2>2. Information we collect</h2><p>When you join the waitlist, we collect your email address and any optional suggestion you choose to share. Our form also uses a hidden website field to help identify automated submissions. We may collect limited technical and usage information through our hosting and analytics providers, such as device, browser, page, and interaction data.</p></section><section><h2>3. How we use information</h2><p>We use the information we collect to manage the waitlist, send relevant Edison updates, respond to your message where appropriate, understand interest in Edison, protect the form from abuse, and improve the website and product.</p></section><section><h2>4. How we share information</h2><p>We do not sell your personal information. We may share information with service providers that help us host Edison, deliver email, provide analytics, secure the website, or operate communications. We may also disclose information where required by law or to protect Edison, its users, or others.</p></section><section><h2>5. Retention and your choices</h2><p>We keep waitlist information for as long as it is reasonably needed for the purposes described above, unless a longer period is required by law. You may ask us to access, correct, or delete your waitlist information, or unsubscribe from future messages, by contacting us at <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></section><section><h2>6. Security and international use</h2><p>We use reasonable safeguards designed to protect information. No online system is completely secure. Edison may process information in countries where our providers operate, which may have different data-protection laws than your location.</p></section><section><h2>7. Children and updates</h2><p>Edison is not directed to children under 13, and we do not knowingly collect personal information from them. We may update this policy as Edison develops; the updated date above will show when changes take effect.</p></section><section><h2>8. Contact</h2><p>For privacy questions, requests, or concerns, email <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></section></LegalShell>;
}

export function TermsOfService() {
  return <LegalShell eyebrow="Edison / terms" title="Terms of Service"><section><h2>1. Agreement to these terms</h2><p>By using the Edison website or joining the waitlist, you agree to these Terms of Service. If you do not agree, please do not use the website or submit information through it.</p></section><section><h2>2. Early access and availability</h2><p>Edison is an early-stage product. The website and waitlist are provided to share information and collect interest. Access to future features is not guaranteed, and we may change, pause, or discontinue any part of the website or waitlist at any time.</p></section><section><h2>3. Your submissions</h2><p>You may submit an email address and optional feedback. Please provide information you are allowed to share and do not submit unlawful, harmful, confidential, or infringing material. You keep ownership of your feedback, but grant Edison a non-exclusive, worldwide, royalty-free right to use it to develop, improve, and communicate about Edison.</p></section><section><h2>4. Acceptable use</h2><p>You may not use the website to interfere with its operation, attempt unauthorized access, submit automated spam, violate applicable law, or harm Edison or others. We may restrict or remove access where we reasonably believe these terms have been breached.</p></section><section><h2>5. Intellectual property</h2><p>The Edison name, logo, website design, text, and other website materials are owned by or licensed to Edison and are protected by applicable intellectual-property laws. You may not copy, modify, distribute, or use them except as allowed by law or with our written permission.</p></section><section><h2>6. Disclaimers and liability</h2><p>The website is provided on an “as is” and “as available” basis. To the fullest extent allowed by law, Edison disclaims warranties of merchantability, fitness for a particular purpose, and non-infringement. Edison will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of the website. Nothing in these terms limits liability that cannot legally be limited.</p></section><section><h2>7. Changes and contact</h2><p>We may update these terms as Edison evolves. Continued use after an update means you accept the revised terms. For questions, email <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></section></LegalShell>;
}
